# Encoding

When organizing and analyzing data in statistics, **nominal** and **ordinal** data are two fundamental types of categorical (non-numerical) data.

The easiest way to tell them apart is to look at whether the **order** of the categories matters.

## 1. Nominal Data (Labels Only)

Nominal data is used to name, label, or classify things into distinct groups. The categories have **no inherent order, ranking, or numerical value**. One category isn't "higher" or "better" than another; they are just different.

- **Key Characteristic:** You cannot sort them in a meaningful logical order (other than alphabetically).
- **Examples:**
- **Eye color:** Brown, Blue, Green, Hazel.
- **Marital status:** Single, Married, Divorced, Widowed.
- **Car brands:** Toyota, Ford, BMW, Tesla.
- **Binary outcomes:** Yes / No, Pass / Fail.

## 2. Ordinal Data (Labels with a Order)

Ordinal data also classifies things into groups, but the categories have a **clear, natural order or ranking**. While we know which category is "more" or "less" than another, we cannot precisely measure the exact *distance* between them.

- **Key Characteristic:** The sequence matters, but the mathematical difference between rankings isn't equal or measurable. (For example, the difference between 1st and 2nd place in a race might be 0.1 seconds, but between 2nd and 3rd it might be 5 seconds).
- **Examples:**
- **Satisfaction ratings:** Dissatisfied, Neutral, Satisfied.
- **Socioeconomic status:** Low-income, Middle-income, High-income.
- **Competition results:** 1st place, 2nd place, 3rd place.
- **Education level:** High School, Bachelor's, Master's, PhD.

## Quick Comparison Summary

| Feature | Nominal Data | Ordinal Data |
| --- | --- | --- |
| **Has Categories?** | Yes | Yes |
| **Ordered/Ranked?** | No | **Yes** |
| **Mathematical Value?** | No | No |
| **Best Measure of Center** | Mode (most frequent) | Median (middle value) or Mode |
| **Core Purpose** | To identify/group | To rank/scale |

In machine learning and data science, **nominal encoding** (often called categorical encoding) is the process of converting categorical variables—like city names, colors, or job titles—into numerical values so that mathematical algorithms can process them.

Because nominal data has no inherent order, how you choose to encode it plays a massive role in model performance.

## Pros and Cons of Nominal Encoding Techniques

There isn't just one way to encode nominal data. The pros and cons depend entirely on the method you choose. The two most common techniques are **One-Hot Encoding** and **Label/Ordinal Encoding** (though using Label Encoding on nominal data is a common trap).

### 1. One-Hot Encoding (The Standard Approach)

This creates a new binary column (0 or 1) for every unique category in your dataset.

- **Pros:**
- **No Fake Hierarchy:** It correctly treats all categories as equally different. The model won't mistakenly think "Blue" is greater than "Red."
- **Works Great with Linear Models:** Algorithms like Linear Regression or Logistic Regression handle these explicit binary boundaries very well.
- **Cons:**
- **The Curse of Dimensionality:** If a column has 100 unique categories (e.g., US States), One-Hot Encoding turns that 1 column into 50 columns. This explodes your dataset size, slows down training, and can cause overfitting.
- **Multicorrelation (The Dummy Variable Trap):** The columns become perfectly predictable from one another, which can break certain statistical models.

### 2. Label Encoding (The Risky Approach)

This simply assigns an arbitrary number to each category (e.g., Red = 1, Blue = 2, Green = 3).

- **Pros:**
- **Space Efficient:** It keeps your dataset memory-light by keeping everything in a single column.
- **Cons:**
- **Introduces Fake Order:** This is the biggest flaw. A machine learning model will look at the numbers and assume $3 \gt 1$ (Green is greater than Red), or that the "average" of Red and Green is Blue $(1 + 3) / 2 = 2$. For nominal data, this is mathematically nonsensical and can ruin your model's accuracy.

## The Crucial Statistical Concept: The Dummy Variable Trap

If you use One-Hot Encoding, you must understand a vital statistical concept called **Multicollinearity**—specifically, the **Dummy Variable Trap**.

### What is Multicollinearity?

Multicollinearity occurs when two or more predictor variables in a statistical model are highly correlated, meaning one can be linearly predicted from the others with a high degree of accuracy.

### How One-Hot Encoding Causes It

Imagine a nominal variable for "Gender" with two categories: `Male` and `Female`. If you One-Hot Encode this, you get two columns:

1. `Is_Male` (1 or 0)
2. `Is_Female` (1 or 0)

If a row has a `1` for `Is_Male`, it *must* have a `0` for `Is_Female`. They are perfectly inversely correlated. Statistically, the second column provides **zero new information**.

Mathematically, this causes severe issues for models like Ordinary Least Squares (OLS) Linear Regression because it makes the design matrix non-invertible. In plain English: **the algorithm's math breaks down**, leading to unstable, wildly fluctuating coefficients.

### The Statistical Solution: $N-1$ Encoding

To avoid this trap, you should always drop one of the encoded columns. If a feature has $N$ unique categories, you only keep $N-1$ dummy columns.

- If `Is_Male` is `0`, the model automatically infers that the person is female. The dropped category becomes the **reference/baseline group** against which all other categories are statistically measured.

Are you preparing this data for a specific type of machine learning model, or are you focusing purely on statistical analysis?

You should use **nominal encoding** whenever your dataset contains categorical variables that have **no inherent ranking, order, or numerical distance** between them, and you need to feed this data into a machine learning algorithm.

Because machine learning models are essentially massive calculators that perform matrix multiplication, they cannot understand the words "Red," "Blue," or "Green"—they require numbers.

However, choosing *which* nominal encoding technique to use depends entirely on the **cardinality** of your data and the **type of algorithm** you are running.

## 1. When to Use One-Hot Encoding

One-Hot Encoding is the default, go-to choice for nominal data under specific conditions.

- **Low-to-Medium Cardinality:** Use it when your nominal feature has a small number of unique categories (e.g., less than 15 or 20). Examples include `Gender` (Male, Female, Non-binary) or `Continent` (Asia, Europe, Africa, etc.).
- **When Using Linear Models or SVMs:** Algorithms like Linear Regression, Logistic Regression, and Support Vector Machines rely on linear decision boundaries. One-Hot Encoding creates a clear, distinct binary geometric space for each category, which these models handle perfectly.
- **When Using Neural Networks:** Deep learning models can easily process the sparse, high-dimensional matrices created by One-Hot Encoding.

## 2. When to Use Target Encoding (or Frequency Encoding)

If you have **high-cardinality** nominal data, One-Hot Encoding will break your model by creating thousands of columns.

- **High Cardinality:** Use this when a nominal variable has dozens, hundreds, or thousands of unique categories. Examples include `Zip Code`, `IP Address`, `Device Model`, or `Job Title`.
- **When Using Tree-Based Algorithms:** Gradient boosting trees (like XGBoost, LightGBM, and CatBoost) or Random Forests excel at handling target-encoded variables because they can easily split the data along the continuous, numeric averages that target encoding provides.

## 3. When to Use Count / Frequency Encoding

This approach replaces each category with the number of times (or percentage of times) it appears in the dataset.

- **When Frequency Itself is a Signal:** Use this when the popularity or rarity of a nominal category tells you something important about the target. For example, in fraud detection, an IP address or credit card country that appears 10,000 times in an hour is highly suspicious compared to one that appears once.

## Decision Matrix: Which Encoding to Use?

| If your nominal data has... | And your ML model is... | **Your best encoding choice is...** |
| --- | --- | --- |
| **Low Cardinality** (e.g., $\le 10$ categories) | Any Model (Linear, Trees, NN) | **One-Hot Encoding** (Drop 1 column for linear models) |
| **High Cardinality** (e.g., $100+$ categories) | Tree-Based (XGBoost, Random Forest) | **Target Encoding** (with smoothing) |
| **High Cardinality** (e.g., $100+$ categories) | Linear Model or Neural Network | **Feature Embedding** (Entity Embeddings) or **Hash Encoding** |
| **Varying Cardinality** | Any Model (Fraud/Anomalies) | **Count / Frequency Encoding** |

## Related Statistical Concept: The Curse of Dimensionality

A critical statistical concept dictating *when* to use which encoding is the **Curse of Dimensionality**.

As you add more features (columns) to a dataset, the volume of the data space grows exponentially, making the available data points incredibly **sparse**.

If you use One-Hot Encoding on a high-cardinality nominal variable (like 500 unique product IDs), you suddenly inject 500 columns of mostly zeros into your dataset. In this massive, sparse high-dimensional space, data points become equidistant from one another.

As a result:

1. **Distance-based algorithms** (like K-Nearest Neighbors or K-Means Clustering) completely fail because they can no longer accurately calculate which points are genuinely "close" to one another.
2. **Models easily overfit**, finding random noise patterns in the sea of zeros that won't generalize to new data.

This statistical reality is exactly why data scientists transition away from One-Hot Encoding and toward Target Encoding or Embeddings as category counts grow.

#### 1. Label encoding (nominal)

In [1]:
# Standard imports for data manipulation and plotting
# - pandas: primary DataFrame structure and utilities
# - seaborn/matplotlib: plotting libraries used for visualizing distributions and encoder outputs
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# Typical outputs: pandas.DataFrame for tabular data; seaborn/matplotlib create plot figures

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("D:/KrishNaikDataScience/LiveProjects/Level4_featureEngg/26_Apr_FeatureEngg_3/house-prices-advanced-regression-techniques/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
# Select the column to encode and inspect its unique categories
col = "MSZoning"
# Printing unique categories shows the distinct nominal values (output: numpy array)
print("Before:", df[col].unique())

Before: <StringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str

In [13]:
print(type(pd.factorize(df[col]))) # Output: tuple (encoded_array, unique_categories)

<class 'tuple'>

In [14]:
print("Before:", df[col].unique())

# Method 1: Pandas factorize
# Encodes the data in the order they appear in the row
df["MSZoning_label"] = pd.factorize(df[col])[0] # Output: numeric array of encoded values; unique categories are stored separately in the tuple at item1

# Method 2: Sklearn LabelEncoder
# sorts unique values alphabetically -> assign number
le = LabelEncoder()
print("Sklearn LabelEncoder:", le.fit_transform(df[col]))
df["MSZoning_label_sklearn"] = le.fit_transform(df[col])

print("After Pandas factorize:", df["MSZoning_label"].unique())
print("After Sklearn:", df["MSZoning_label_sklearn"].unique())

Before: <StringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str
Sklearn LabelEncoder: [3 3 3 ... 3 3 3]
After Pandas factorize: [0 1 2 3 4]
After Sklearn: [3 4 0 1 2]

#### 2. Label Encoding (ordinal)

In [15]:
# Ordinal encoding: specify a meaningful category order and map to integers
from sklearn.preprocessing import OrdinalEncoder

# Provide a controlled order (list of categories); necessary for ordinal relationships
# self defined order as  example taken here
ordinal_order = [['C (all)', 'RM', 'RH', 'RL', 'FV']] # List of lists format is required by OrdinalEncoder for multiple columns; here we have one column
oe = OrdinalEncoder(categories=ordinal_order)
# fit_transform expects 2D input for a single column: df[[col]] -> returns 2D array of numeric codes
df["MSZoning_ordinal"] = oe.fit_transform(df[[col]])

# Print original and encoded values (encoded output is numeric values representing order)
print("Before:", df[col].unique())
print("After OrdinalEncoder (with order):", df["MSZoning_ordinal"].unique())

Before: <StringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str
After OrdinalEncoder (with order): [3. 1. 0. 4. 2.]

#### 3. OHE (One Hot Encoding)

In [16]:
# One-Hot Encoding using pandas.get_dummies -> produces binary indicator columns for each category
col = "MSZoning"
print("Before:", df[col].unique())

# Create the one-hot columns (DataFrame) using pandas utility
mszoning_ohe_pandas = pd.get_dummies(df[col], prefix="MSZoning")
# Concatenate with original column for a compact display and drop duplicates to show one row per category
pandas_comparison = pd.concat([df[col], mszoning_ohe_pandas], axis=1)
unique_pandas_ohe = pandas_comparison.drop_duplicates(subset=[col]).reset_index(drop=True)
# Output: DataFrame showing each original category and its one-hot indicator columns
unique_pandas_ohe

Before: <StringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str

,MSZoning,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,RL,False,False,False,True,False
1,RM,False,False,False,False,True
2,C (all),True,False,False,False,False
3,FV,False,True,False,False,False
4,RH,False,False,True,False,False

In [ ]:
# Method 2: sklearn OneHotEncoder (produces numpy array or sparse matrix depending on config)
from sklearn.preprocessing import OneHotEncoder

# Configure encoder: `sparse_output=False` returns dense numpy array; `drop=None` keeps all categories
# dense numpy array will contain all the zeros and ones for the one-hot encoding of each category. This will require more memory for large datasets, but is easier to work with for small datasets.
ohe = OneHotEncoder(sparse_output=False, drop=None)
# fit_transform returns array shape (n_samples, n_categories)
mszoning_ohe_sklearn = ohe.fit_transform(df[[col]])
print("Sklearn OneHotEncoder:", mszoning_ohe_sklearn)
# Convert array to DataFrame for display with feature names generated by the encoder
ohe_df = pd.DataFrame(mszoning_ohe_sklearn, columns=ohe.get_feature_names_out([col]))
# Concatenate and deduplicate to show mapping from category to one-hot columns
sklearn_comparison = pd.concat([df[col], ohe_df], axis=1)
unique_sklearn_ohe = sklearn_comparison.drop_duplicates(subset=[col]).reset_index(drop=True)
# Output: DataFrame showing one-hot encoded representation per original category
unique_sklearn_ohe

Sklearn OneHotEncoder: [[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]

,MSZoning,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,RL,0.0,0.0,0.0,1.0,0.0
1,RM,0.0,0.0,0.0,0.0,1.0
2,C (all),1.0,0.0,0.0,0.0,0.0
3,FV,0.0,1.0,0.0,0.0,0.0
4,RH,0.0,0.0,1.0,0.0,0.0

In [19]:
# Demo of OneHotEncoder returning a sparse matrix to preserve memory for high-cardinality data
df_sparse_ohe = pd.DataFrame({'Color': ['Red', 'Green', 'Blue']})

# Configure to return sparse output (scipy sparse matrix). This is important for large vocabularies/features.
ohe_sparse = OneHotEncoder(sparse_output=True)
color_encoded_sparse = ohe_sparse.fit_transform(df_sparse_ohe[['Color']])

# Display the type and both sparse and dense representations for clarity
print("Sparse Output (Type):", type(color_encoded_sparse))
# Note: avoid converting large sparse matrices to dense in practice (OOM risk)
print("\nSparse Matrix Output:\n", color_encoded_sparse)
print("\nSparse Matrix as a dense array:\n", color_encoded_sparse.toarray())

Sparse Output (Type): <class 'scipy.sparse._csr.csr_matrix'>

Sparse Matrix Output:
 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0

Sparse Matrix as a dense array:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

#### 4. Target Encoding

**Target Encoding** (also known as Mean Encoding) is a highly effective technique for converting nominal categorical variables into numerical values. Instead of creating new columns or assigning arbitrary numbers, Target Encoding replaces each category with the **expected value of the target variable** for that specific category.

For a binary classification problem (e.g., predicting if a customer will churn: 1 for Yes, 0 for No), a category is replaced by the **mean of the target variable** (the probability of churning) for that category.

## How It Works: A Quick Example

Imagine you are predicting house prices (Target) based on the City (Nominal Feature).

| City (Feature) | House Price (Target) | Target Encoded City |
| --- | --- | --- |
| New York | $500,000 | **$450,000** |
| New York | $400,000 | **$450,000** |
| Miami | $300,000 | **$250,000** |
| Miami | $200,000 | **$250,000** |

- The average house price in New York is $450,000. Every instance of "New York" is replaced with `450000`.
- The average house price in Miami is $250,000. Every instance of "Miami" is replaced with `250000`.

## Pros and Cons of Target Encoding

### Pros:

- **No Dimensionality Explosion:** Unlike One-Hot Encoding, Target Encoding always outputs exactly **one column**, regardless of whether your category has 5 or 5,000 unique values. This saves massive amounts of memory and computational time.
- **Captures Strong Relationships:** It directly injects the relationship between the feature and the target into the dataset, which often gives tree-based models (like XGBoost or LightGBM) a massive performance boost.

### Cons:

- **Severe Risk of Overfitting:** Because this method uses the target variable to encode the feature, it leaks information about the target into the training data. The model can easily memorize these encodings rather than learning generalized patterns.
- **The "Rare Category" Problem:** If a category appears only once in your dataset (e.g., a tiny town with one mansion priced at $2,000,000), Target Encoding will assign it a value of `2000000`. This completely distorts the data based on a single outlier.

## When to Use Target Encoding

You should opt for Target Encoding when:

1. You have **high-cardinality nominal features** (columns with dozens, hundreds, or thousands of unique categories, like zip codes, IP addresses, or product IDs) where One-Hot Encoding would create too many columns.
2. You are using **tree-based machine learning algorithms** (Gradient Boosting, Random Forests) which can exploit the monotonic relationship created by target encoding beautifully.

## Crucial Statistical Concept: Empirical Bayes Smoothing

To fix the "Rare Category" problem and prevent drastic overfitting, statisticians and data scientists use a technique called **Smoothing** (strongly rooted in **Empirical Bayes estimation**).

Instead of relying solely on the category's specific average, smoothing blends the category average with the **global average** of the entire dataset.

### The Math Behind It

The smoothed value for a category is calculated using a weighted average:

$$
\hat{x}_i = \lambda(n_i) \cdot \mu_i + (1 - \lambda(n_i)) \cdot \mu_{\text{global}}
$$

Where:

- $n_i$ is the number of times category $i$ appears in the dataset.
- $\mu_i$ is the raw target mean for category $i$.
- $\mu_{\text{global}}$ is the global target mean across the entire dataset.
- $\lambda(n_i)$ is a weight function (a value between 0 and 1) that depends on the sample size $n_i$.

### How It Solves the Problem

- **For a common category (high $n_i$):** $\lambda$ is close to 1. The model trusts the category's specific mean ($\mu_i$) because there is plenty of data to back it up.
- **For a rare category (low $n_i$):** $\lambda$ is close to 0. The formula shrinks the encoded value toward the **global mean** ($\mu_{\text{global}}$). If that tiny town only has one data point, the encoding pulls its value back down toward the average house price of the whole country, preventing the model from making wild assumptions based on a single sample.

Are you dealing with a specific high-cardinality feature in a project right now, or are you exploring this for algorithmic modeling?

In [ ]:
# If category_encoders is missing, install it. Uncomment to run in notebook environment
# !pip install category_encoders

In [20]:
# Import category_encoders to access advanced encoders like TargetEncoder and CountEncoder
# Output: module object; encoder classes provide fit/transform methods
import category_encoders as ce

In [21]:
# Prepare variables for target encoding demo
col = "Neighborhood"
target_col = "SalePrice"
# Print unique categories to inspect cardinality (output: numpy array)
print("Before:", df[col].unique())

Before: <StringArray>
['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',  'NWAmes',
 'OldTown', 'BrkSide',  'Sawyer', 'NridgHt',   'NAmes', 'SawyerW',  'IDOTRR',
 'MeadowV', 'Edwards',  'Timber', 'Gilbert', 'StoneBr', 'ClearCr', 'NPkVill',
 'Blmngtn',  'BrDale',   'SWISU', 'Blueste']
Length: 25, dtype: str

In [ ]:
# Fit a TargetEncoder which replaces categories with smoothed mean of the target variable
# This tends to produce numeric values that capture target-category relationships (output: numeric column)
target_enc = ce.TargetEncoder(cols=[col])
df["Neighborhood_target"] = target_enc.fit_transform(df[col], df[target_col])
# Create mapping table for inspection: category -> encoded numeric value
unique_neighborhood_target = df[[col, "Neighborhood_target"]].drop_duplicates().reset_index(drop=True)
unique_neighborhood_target

   Neighborhood  Neighborhood_target
0       CollgCr        197965.734807
1       Veenker        197643.209810
2       Crawfor        209344.287867
3       NoRidge        318453.591177
4       Mitchel        157555.763763
5       Somerst        225319.439258
6        NWAmes        189009.693995
7       OldTown        128230.118126
8       BrkSide        126061.309722
9        Sawyer        136991.546950
10      NridgHt        315819.259117
11        NAmes        145847.080044
12      SawyerW        186444.004409
13       IDOTRR        112604.177463
14      MeadowV        145878.781837
15      Edwards        128237.373454
16       Timber        233548.253290
17      Gilbert        192821.904993
18      StoneBr        261578.109175
19      ClearCr        202754.908915
20      NPkVill        171374.451021
21      Blmngtn        186857.589353
22       BrDale        150249.918749
23        SWISU        157062.431877
24      Blueste        174761.853014

In [ ]:
# Placeholder: suggested assignment to scale the target-encoded column. 
# We got the target encoded values in the previous step, but they may have a wide range. Scaling them can help with model convergence
#  and interpretability. You can use StandardScaler or MinMaxScaler from sklearn.preprocessing to scale the "Neighborhood_target" column.
# Example (not executed here):
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# df['Neighborhood_target_scaled'] = scaler.fit_transform(df[['Neighborhood_target']])
# Output: new column with standardized numeric values

#### 5. Frequency Encoding

**Frequency Encoding** (also known as Count Encoding) is a straightforward and effective technique for handling nominal categorical variables. Instead of creating new binary columns or relying on the target variable, it replaces each category with the number of times it appears in the dataset (its count) or the percentage of its occurrence (its frequency).

## How It Works: A Quick Example

Imagine a column for `Car Brand` in a dataset of 100 vehicles:

| Car Brand (Feature) | Count in Dataset | Frequency Encoding (Count) | Frequency Encoding (Percentage) |
| --- | --- | --- | --- |
| Toyota | 60 times | **60** | **0.60** |
| Ford | 30 times | **30** | **0.30** |
| Tesla | 10 times | **10** | **0.10** |

Every time "Toyota" appears in your rows, it is simply replaced by `60` (or `0.60`).

## Pros and Cons of Frequency Encoding

### Pros:

- **No Dimensionality Explosion:** Just like Target Encoding, Frequency Encoding keeps your data memory-light by outputting exactly **one column** per categorical feature, avoiding the thousands of sparse columns that One-Hot Encoding might produce.
- **Blends Group Sizes Intuitively:** It preserves a very specific piece of information: how common or rare a category is.
- **Computationally Efficient:** It only requires a basic frequency mapping step (a single pass to count the occurrences), making it incredibly fast to compute even on massive datasets.

### Cons:

- **The "Collision" Problem:** If two entirely different categories appear the exact same number of times in your dataset, they will get the exact same encoded value. For example, if "BMW" also appears exactly 10 times, both Tesla and BMW will be encoded as `10`. The model loses the ability to tell them apart.
- **Ignores the Target Variable:** Unlike Target Encoding, Frequency Encoding doesn't look at what you are trying to predict. If a category's popularity has no correlation with the target variable, this encoding inserts useless information into the model.

## When to Use Frequency Encoding

You should choose Frequency Encoding when:

1. **You have high-cardinality nominal features** (like Zip Codes, User IDs, or Product Categories) where One-Hot Encoding is out of the question.
2. **Frequency itself is a strong predictor.** This is incredibly common in specific domains:
- **Fraud Detection:** If an IP address or Credit Card Country appears 50,000 times in an hour, its high frequency is a massive red flag.
- **Web Analytics / E-commerce:** Highly frequent search terms or product views behave differently than rare, "long-tail" search items.
3. **You are using tree-based machine learning algorithms** (like Random Forests or Gradient Boosting) because they can easily create splits based on popularity (e.g., "Is this product category in the top 10% of popularity?").

## Related Statistical Concepts

### 1. Power Law / Zipf's Law (The Long Tail)

In many real-world datasets, categorical frequencies do not follow a uniform or normal distribution. Instead, they follow a **Power Law distribution** (often generalized as Zipf's Law or the 80/20 rule).

This statistical principle states that a small number of categories will appear an overwhelming majority of the time, while a massive number of categories will appear very rarely (known as the "Long Tail").

Frequency encoding maps this phenomenon into a numerical scale. By converting categories into their frequencies, the encoder groups the massive sea of rare "Long Tail" attributes into a clustered numeric space (near 0 or 1, depending on count vs. percentage), allowing your machine learning model to easily treat rare categories as a collective group rather than learning individual, noisy patterns for each one.

### 2. Frequency vs. Probability (The Law of Large Numbers)

When you use the percentage variation of Frequency Encoding, you are calculating the **empirical probability** (or relative frequency) of that category occurring within your sample space:

$$
P(\text{Category}) = \frac{\text{Count of Category}}{\text{Total Number of Rows}}
$$

According to the **Law of Large Numbers**, as your dataset grows larger, this sample relative frequency will converge closer to the true, theoretical probability of that category existing in the real world. This makes the frequency representation highly stable and reliable when training on large production-scale datasets, though it can remain volatile and prone to noise if your training sample size is too small.

In [22]:
# Frequency encoding example: inspect categories before computing frequencies
col = "Neighborhood"
print("Before:", df[col].unique())
# Output: numpy array of unique neighborhood names

Before: <StringArray>
['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',  'NWAmes',
 'OldTown', 'BrkSide',  'Sawyer', 'NridgHt',   'NAmes', 'SawyerW',  'IDOTRR',
 'MeadowV', 'Edwards',  'Timber', 'Gilbert', 'StoneBr', 'ClearCr', 'NPkVill',
 'Blmngtn',  'BrDale',   'SWISU', 'Blueste']
Length: 25, dtype: str

In [23]:
# Method 1: create a frequency mapping using pandas.value_counts
# Output: dictionary mapping category -> observed count
freq_encoding = df[col].value_counts().to_dict()

In [25]:
# Show the frequency mapping dictionary (output: python dict)
freq_encoding

{'NAmes': 225,
 'CollgCr': 150,
 'OldTown': 113,
 'Edwards': 100,
 'Somerst': 86,
 'Gilbert': 79,
 'NridgHt': 77,
 'Sawyer': 74,
 'NWAmes': 73,
 'SawyerW': 59,
 'BrkSide': 58,
 'Crawfor': 51,
 'Mitchel': 49,
 'NoRidge': 41,
 'Timber': 38,
 'IDOTRR': 37,
 'ClearCr': 28,
 'StoneBr': 25,
 'SWISU': 25,
 'MeadowV': 17,
 'Blmngtn': 17,
 'BrDale': 16,
 'Veenker': 11,
 'NPkVill': 9,
 'Blueste': 2}

In [26]:
# Map each category to its frequency count and store as new column (output: numeric column)
df["Neighborhood_freq"] = df[col].map(freq_encoding)

In [27]:
# Display mapping of category to computed frequency (DataFrame output)
df[["Neighborhood", "Neighborhood_freq"]].drop_duplicates().reset_index(drop=True)

   Neighborhood  Neighborhood_freq
0       CollgCr                150
1       Veenker                 11
2       Crawfor                 51
3       NoRidge                 41
4       Mitchel                 49
5       Somerst                 86
6        NWAmes                 73
7       OldTown                113
8       BrkSide                 58
9        Sawyer                 74
10      NridgHt                 77
11        NAmes                225
12      SawyerW                 59
13       IDOTRR                 37
14      MeadowV                 17
15      Edwards                100
16       Timber                 38
17      Gilbert                 79
18      StoneBr                 25
19      ClearCr                 28
20      NPkVill                  9
21      Blmngtn                 17
22       BrDale                 16
23        SWISU                 25
24      Blueste                  2

In [28]:
# Method 2: use category_encoders CountEncoder which provides a transformer API
# Output: encoder object; fit_transform returns numeric encodings for each row
count_enc = ce.CountEncoder(cols=[col])
# Note: CountEncoder expects a DataFrame input in many versions; passing a Series may still work depending on implementation
df["Neighborhood_freq_ce"] = count_enc.fit_transform(df[col])
# Create a mapping DataFrame for inspection (DataFrame output)
unique_neighborhood_frequency_encoding = df[[col, "Neighborhood_freq_ce"]].drop_duplicates().reset_index(drop=True)
unique_neighborhood_frequency_encoding

   Neighborhood  Neighborhood_freq_ce
0       CollgCr                   150
1       Veenker                    11
2       Crawfor                    51
3       NoRidge                    41
4       Mitchel                    49
5       Somerst                    86
6        NWAmes                    73
7       OldTown                   113
8       BrkSide                    58
9        Sawyer                    74
10      NridgHt                    77
11        NAmes                   225
12      SawyerW                    59
13       IDOTRR                    37
14      MeadowV                    17
15      Edwards                   100
16       Timber                    38
17      Gilbert                    79
18      StoneBr                    25
19      ClearCr                    28
20      NPkVill                     9
21      Blmngtn                    17
22       BrDale                    16
23        SWISU                    25
24      Blueste                     2